### ISSUE TITLE
Add aggregate queries and aggregate joins

### ISSUE THREAD

**Issue by danielrearden** [danielrearden/sqlmancer#1]
Add ability to query aggregate values and do aggregate joins. In order to support querying aggregate values, a new aggregate query builder would need to be added and included in the database client. The `findOne`, `findMany` and `findById` query builders would need to support a new join method. Either the existing `@join` directive would need to be modified to support aggregate joins, or else a new directive would need to be added.

The resulting query might look something like this:

```
{
  modelsAggregate {
    count
    min {
      someField
    }
    avg {
      someOtherField
    }
  }
}
```

This mirrors existing implementations, like Hasura's, but results in a very nested structure. Alternatively, we could expose a single field with an input, for example:

```
{
  modelsCount: modelsAggregate(func: count)
  minSomeField: modelsAggregate(func: min, field: someField)
  avgSomeOtherField: modelsAggregate(func: avg, field: someOtherField)
}
```

The biggest downside is that using a single field like this would mean using Float even when Int would be appropriate (e.g. for count) but maybe we can live with that.

**Comment by lishine** [comment]
This option is not clear to me:
>{
  modelsCount: modelsAggregate(func: count)
  minSomeField: modelsAggregate(func: min, field: someField)
  avgSomeOtherField: modelsAggregate(func: avg, field: someOtherField)
}
The biggest downside is that using a single field like this would mean using Float even when Int would be appropriate (e.g. for count) but maybe we can live with that.

I want to point another disadvantage of hasura api, this is how it looks:
```
const queryDevice = /* GraphQL */ `
    query($user_id: Int!) {
        device(where: { device_owners: { user_id: { _eq: $user_id } } }, limit: 1) {
            device_name
        }
        device_owner_aggregate(where: { user_id: { _eq: $user_id } }) {
            aggregate {
                count
            }
        }
    }
`
```

You see, you have to specify the filtering twice per query.
But maybe all the explicitness is preferred... They choose it for a reason but maybe not because it is the best, just because they had to support some existing implementation.

**Comment by lishine** [comment]
Maybe something like
```
    query Orders($limit: Int, $offset: Int) {
        orders {
            aggregate  {
                count
                min {
                    someField
                }
                avg {
                    someOtherField
                }
            }
            nodes {
                field1
                field2
            }
        }

```

**Comment by lishine** [comment]
Why this does not work:
```
    type Order @model(table: "orders", pk: "id") {
        id: ID!
        createdAt: String!
    }
    type Orders {
        nodes: [Order!]
        count: Int
    }
    type Query {
        orders(limit: Int, offset: Int): Orders @where @orderBy
    }
```
nor this
```
    type Order @model(table: "orders", pk: "id") {
        id: ID!
        createdAt: String!
    }
    type Orders {
        nodes: [Order!]
        count: Int
    }
    type Query {
        orders(limit: Int, offset: Int): Orders @where(model: "Order") @orderBy(model: "Order")
    }
```

**Comment by lishine** [comment]
I tried to use the orders(limit: Int, offset: Int): [Order!] @where @orderBy
But to extend Order with count:
```
    type Order @model(table: "orders", pk: "id") {
        id: ID!
        createdAt: String!
        count: Int! @depend(on: ["id"])
    }
```
It required me to insert some on parameter and it did not succeed anyway. Don't know how to extend the type.

**Comment by lishine** [comment]
Actually it is fine, I just add another resolver ordersCount and request it one go:
```
query {
  orders(limit: 2) {
      id
      createdAt
  }
  ordersCount
}
```

**Comment by danielrearden** [comment]
Added with dad5c573c9c50d3e64db0ee255b38d6ec74559d1

**Comment by danielrearden** [comment]
@lishine Sorry for the late response. I've been swamped and wanted to get the next release out ASAP.

I liked your suggestion to use Hasura-like aggregate fields. I went tried to implement something along those lines, but ultimately settled on a more robust pagination mechanism that incorporates aggregation. Simple pagination is still supported, but now you can also create fields that support queries like this:

```graphql
{
  orders {
    results {
      id
    }
    hasMore
    aggregate {
      count
      sum {
        total
      }
    }
  }
}
```

The docs now include sections on both [pagination](https://sqlmancer.netlify.app/pagination) and [aggregation](https://sqlmancer.netlify.app/aggregation). I'm still not really happy with the overall flow of the docs -- it's all kind of disjointed right now. But I'm hoping I can give them some TLC soon.

Let me know if you have a chance to check out v0.2.0 and have any feedback!

**Comment by lishine** [comment]
Great to know that you are working on it! I very appreciative your community support!
I like your solution. It is similar to what I suggested above, better than hasura.

**Comment by lishine** [comment]
> Why this does not work:
> 
> ```
>     type Order @model(table: "orders", pk: "id") {
>         id: ID!
>         createdAt: String!
>     }
>     type Orders {
>         nodes: [Order!]
>         count: Int
>     }
>     type Query {
>         orders(limit: Int, offset: Int): Orders @where(model: "Order") @orderBy(model: "Order")
>     }
> ```
> 
> sqlmancer generator gives error:
> ` Type named "Orders" isn't a valid model. Did you include the @model directive?`
> why it @where depend on the return type of query ?
> It works only with `orders(limit: Int, offset: Int): [Order] @where @orderBy`
> But I want to return the count in one go
> 
> nor this
> 
> ```
>     type Order @model(table: "orders", pk: "id") {
>         id: ID!
>         createdAt: String!
>     }
>     type Orders {
>         nodes: [Order!]
>         count: Int
>     }
>     type Query {
>         orders(limit: Int, offset: Int): Orders @where @orderBy
>     }
> ```
> 
> ```
>             let nodes = await client.models.Order.findMany()
>                 .resolveInfo(info)
>                 .limit(limit || 10)
>                 .offset(offset || 0)
>                 .execute()
> ```
> 
> It gives `nodes [ { '?column?': null }, { '?column?': null } ]`

This one still not clear to me.
Why @where cares about return type of a query?

**Comment by danielrearden** [comment]
@lishine That looks like it was a bug, but it should now be fixed. I just tested your type definitions with the latest release and it worked fine. `@where` *will* use the return type of the field, but only if the `model` argument is not provided.

FWIW, there's also a `@many` directive now that can be used in place of using `@where`, `@orderBy`, `@limit` and `@offset`.

**Comment by danielrearden** [comment]
Also we have a [Discord channel](https://discord.com/channels/625400653321076807/710279654140805230) now if you prefer to chat on there :)
