### ISSUE TITLE
Is there a Roadmap?

### ISSUE THREAD

**Issue by TSiege** [danielrearden/sqlmancer#85]
This project looks really great, and it's a brilliant use of directives. I saw that it's in beta, and I wondering if there was a roadmap and timeline for a first major cut. It looks like a much better fit than say `join-monster` for my needs.

**Comment by TSiege** [comment]
Nvm I found it! https://github.com/danielrearden/sqlmancer/milestones

**Comment by danielrearden** [comment]
👍 Additional feedback and contributions are always welcome!
